### ISSUE TITLE
Guides vs. All Results

### ISSUE THREAD

**Issue by Trott** [ucsf-ckm/search.library.ucsf.edu#22]
If you search for "medicine", you get three results in the Guides box. If you then click on "All Results", you can dozens.

This is because the guides search uses the widget API provided by SpingShare. I'm guessing this is not a discrepancy we actually want and would prefer to have the results in the box match what's on the actual Guides search page.

Amirite? /cc @mizejewski

**Comment by mizejewski** [comment]
Hmmm...not sure why it only displays 3 results instead of 5 for a start. Does the API let you choose that number? Are you using the API "GET guides: Returns guides for your institution?" Or the widgets search box?

If you search LibGuides directly, you get the same long list because "medicine" shows up in the title, tags, or descriptions of many guides. The API doesn't say what it searches though.

More strange is when I search the more specific "evidence based" -- in LibGuides, I get 29 results -- but zero here. Something strange is going on...

Another unrelated thing I noticed when searching "medicine." Result Library info: Journal of Visualized Experiments (JoVE) is a database, so shouldn't it show up there instead?

**Comment by Trott** [comment]
Searching widgets. I'm just going to switch to scraping the search page so that at least the results are the same.

Databases vs. library info: They are searching different things. Databases is not just a narrowed view of the library search. It is an entirely different set of metadata it searches through. This will hopefully be self-correcting over time as we re-implement databases in a more straightforward fashion.

**Comment by Trott** [comment]
OK, this got waaaaay more complicated than I wanted. But it works now.
